In [1]:
import numpy as np

In [2]:
np.array([5,9,13])

array([ 5,  9, 13])

In [3]:
type([ 5,  9, 13])

list

In [4]:
a=np.array([[1,2],[3,4],[4,5]])
print(a.dtype)
print(a)

int32
[[1 2]
 [3 4]
 [4 5]]


In [5]:
a

array([[1, 2],
       [3, 4],
       [4, 5]])

In [6]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [7]:
np.array(np.mat('1,2,3 ; 3,4,5 ; 5,6,7'))

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [8]:
a=[1,2]
np.array(a)

array([1, 2])

In [9]:
b=np.asarray(a)

In [10]:
b

array([1, 2])

# data type

In [11]:
my_list=[1,2,3]
arr=np.array(my_list)
print("Type/class of this object:",type(arr))
print("Here is the vector\n---------------\n",arr)

Type/class of this object: <class 'numpy.ndarray'>
Here is the vector
---------------
 [1 2 3]


In [12]:
my_mat=([1,2,3],[4,5,6],[7,8,9])
mat=np.array(my_mat)

print("Type/class of this object:",type(mat))
print("here is the matrix\n-------------\n",mat,"\n-----------")
print("Dimension of this matrix:",mat.ndim,sep='')
print("size of this matrix:",mat.size, sep='')
print("shape of this matrix:",mat.shape)
print("Data type of this matrix:",mat.dtype)

Type/class of this object: <class 'numpy.ndarray'>
here is the matrix
-------------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
-----------
Dimension of this matrix:2
size of this matrix:9
shape of this matrix: (3, 3)
Data type of this matrix: int32


# arange and linspace

In [13]:
list(range(2,10.5,4))

TypeError: 'float' object cannot be interpreted as an integer

In [14]:
a=np.arange(2,10.5,0.4) # start point,endpoint,step size
a

array([ 2. ,  2.4,  2.8,  3.2,  3.6,  4. ,  4.4,  4.8,  5.2,  5.6,  6. ,
        6.4,  6.8,  7.2,  7.6,  8. ,  8.4,  8.8,  9.2,  9.6, 10. , 10.4])

In [15]:
print("every 5th number from 50 in reverse order\n",np.arange(50,0,-5))

every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5]


In [16]:
a[::-1]

array([10.4, 10. ,  9.6,  9.2,  8.8,  8.4,  8. ,  7.6,  7.2,  6.8,  6.4,
        6. ,  5.6,  5.2,  4.8,  4.4,  4. ,  3.6,  3.2,  2.8,  2.4,  2. ])

In [17]:
print ("linearly spaced number between 1and 5\n------------------")
print(np.linspace(10,40,5))   #start,stop,no of deta in between(start&stop)

linearly spaced number between 1and 5
------------------
[10.  17.5 25.  32.5 40. ]


# Matrix creation

In [18]:
print("vector of zeroes\n------------------")
print(np.zeros(5))

vector of zeroes
------------------
[0. 0. 0. 0. 0.]


In [19]:
print("vector of zeroes\n------------------")
print(np.zeros((5,6)))

vector of zeroes
------------------
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [20]:
print("vector of ones\n------------------")
print(np.ones(10))

vector of ones
------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [21]:
print("vector of ones\n------------------")
print(np.ones((5,6)))

vector of ones
------------------
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [22]:
print("matrix of 5's\n------------------------")
print(5*np.ones((5,6)))

matrix of 5's
------------------------
[[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]


In [23]:
mat1=np.eye(4)
print("identify matrix of dimension",mat1.shape)
print(mat1)

identify matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [24]:
np.linspace(2.0,3.0,4 ,endpoint=True)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [25]:
np.linspace(2.0,3.0,num=4 ,endpoint=False)

array([2.  , 2.25, 2.5 , 2.75])

In [26]:
np.linspace(2.23456 , 10.3587645 , num=4)

array([ 2.23456   ,  4.94262817,  7.65069633, 10.3587645 ])

In [27]:
np.linspace(2.23456 , 10.3587645 , num=4 , retstep=True)

(array([ 2.23456   ,  4.94262817,  7.65069633, 10.3587645 ]),
 2.7080681666666666)

In [28]:
x=np.arange(30).reshape(6,5)

In [29]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

# Random number generation

In [30]:
print("Randon number generation(from uniform distribution)")
print(np.random.rand(10,6))

Randon number generation(from uniform distribution)
[[0.40687361 0.82341415 0.1534251  0.52794341 0.56682344 0.39563742]
 [0.65091632 0.8801749  0.54196421 0.72876645 0.11219826 0.94442794]
 [0.16911289 0.18980736 0.78976649 0.80620039 0.93811382 0.00285599]
 [0.78837807 0.0951342  0.47678376 0.78207681 0.92302295 0.66201966]
 [0.05171707 0.52218021 0.28283749 0.75188866 0.54609899 0.1517959 ]
 [0.37945292 0.85201929 0.75865919 0.81927356 0.00231911 0.92994434]
 [0.68115096 0.42327525 0.20099115 0.14679957 0.26316473 0.46168902]
 [0.56920253 0.66960349 0.96084855 0.31117238 0.10975587 0.48587872]
 [0.97781705 0.16936267 0.53980575 0.94041033 0.65408044 0.14391316]
 [0.05921879 0.10433329 0.48362023 0.83596972 0.75692697 0.65665155]]


In [31]:
print("Number from normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(10,6))

Number from normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-0.25408052  0.8216789   0.77106201  0.05331119 -0.01638103  0.153177  ]
 [ 0.92233875 -1.11019333 -0.43351639 -0.02625336  0.43273144 -0.781539  ]
 [ 0.34996362  0.38562691  1.48930979 -1.21082594  0.04412877  0.30322162]
 [ 0.21048104 -0.92744492 -0.54430813  1.86499342  1.35556211  0.39008318]
 [ 1.0925637  -1.10777007  0.80178068  0.93990253  0.2451874  -0.92067713]
 [ 0.16004699 -0.3193815   1.50647111 -0.84797615 -1.13102507 -0.35728121]
 [-0.81859864  0.94706222  1.17448752  0.37726425  1.15988813  0.46223805]
 [ 1.24537896 -1.32304081 -0.37439967 -0.3881894   0.6710033  -0.52401482]
 [-0.9387985   0.46784134 -0.97731399  0.54332045 -1.16896051  0.38991102]
 [-2.89911329  0.14828527 -0.84997815  1.1278505  -1.68928338  0.42024337]]


In [32]:
print("Random integer vector:",np.random.randint(10,100,50)) # randint(low,high,how many data wantp)

Random integer vector: [28 66 60 54 71 12 73 86 53 50 50 62 65 57 21 54 94 79 96 27 47 79 57 85
 92 67 57 55 39 12 61 22 56 74 54 97 57 42 61 12 91 27 84 52 74 20 11 12
 57 81]


In [33]:
print("\nRandom integer matrix")
print(np.random.randint(1,30,(6,7)))


Random integer matrix
[[ 7  7 15 26 24  2  4]
 [28 23 28 19  8 12 18]
 [ 2  7 24 14  3 20 16]
 [ 9  6 14 25 23 12  7]
 [29  6 27 12 28 20 23]
 [18 25 12 22  5  3  3]]


In [34]:
print("\n20 sample drawn from a dice throw:",np.random.randint(1,7,20))


20 sample drawn from a dice throw: [3 5 4 3 2 1 6 3 1 5 6 2 4 6 4 4 1 1 1 2]


# Reshaping

In [35]:
from numpy.random import randint as ri
a=ri(1,99,30)

In [36]:
a

array([42, 56, 43, 78, 95, 52, 86, 46, 77,  6, 11, 18, 76, 32, 58, 75, 74,
       61, 14, 26, 49, 72, 42, 19, 81, 75, 69, 14, 94, 77])

In [37]:
b=a.reshape(2,5,3)
b

array([[[42, 56, 43],
        [78, 95, 52],
        [86, 46, 77],
        [ 6, 11, 18],
        [76, 32, 58]],

       [[75, 74, 61],
        [14, 26, 49],
        [72, 42, 19],
        [81, 75, 69],
        [14, 94, 77]]])

In [38]:
c=a.reshape(6,5)
c

array([[42, 56, 43, 78, 95],
       [52, 86, 46, 77,  6],
       [11, 18, 76, 32, 58],
       [75, 74, 61, 14, 26],
       [49, 72, 42, 19, 81],
       [75, 69, 14, 94, 77]])

In [39]:
print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 5, 3)
Shape of c: (6, 5)


In [40]:
print("\na lokk like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb lokk like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc lokk like\n",'-'*20,"\n",c,"\n",'-'*20)


a lokk like
 -------------------- 
 [42 56 43 78 95 52 86 46 77  6 11 18 76 32 58 75 74 61 14 26 49 72 42 19
 81 75 69 14 94 77] 
 --------------------

b lokk like
 -------------------- 
 [[[42 56 43]
  [78 95 52]
  [86 46 77]
  [ 6 11 18]
  [76 32 58]]

 [[75 74 61]
  [14 26 49]
  [72 42 19]
  [81 75 69]
  [14 94 77]]] 
 --------------------

c lokk like
 -------------------- 
 [[42 56 43 78 95]
 [52 86 46 77  6]
 [11 18 76 32 58]
 [75 74 61 14 26]
 [49 72 42 19 81]
 [75 69 14 94 77]] 
 --------------------


In [41]:
A=ri(1,100,10) #vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='quicksort'))


Vector of random integers
 -------------------------------------------------- 
 [99  8 73 29 37 21 53  9 34 31]

Here is the sorted vector
 -------------------------------------------------- 
 [ 8  9 21 29 31 34 37 53 73 99]


In [42]:
M=ri(1,100,25).reshape(5,5)
print("\n5X5 matrix of rendom integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M)) #Default axis=1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))


5X5 matrix of rendom integers
 -------------------------------------------------- 
 [[57 86 62 20 21]
 [ 6 76 93 15 86]
 [42 77 89 27 22]
 [47 23 80 88 74]
 [16 79 39 51 18]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[20 21 57 62 86]
 [ 6 15 76 86 93]
 [22 27 42 77 89]
 [23 47 74 80 88]
 [16 18 39 51 79]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 6 23 39 15 18]
 [16 76 62 20 21]
 [42 77 80 27 22]
 [47 79 89 51 74]
 [57 86 93 88 86]]


In [43]:
a

array([42, 56, 43, 78, 95, 52, 86, 46, 77,  6, 11, 18, 76, 32, 58, 75, 74,
       61, 14, 26, 49, 72, 42, 19, 81, 75, 69, 14, 94, 77])

In [44]:
b

array([[[42, 56, 43],
        [78, 95, 52],
        [86, 46, 77],
        [ 6, 11, 18],
        [76, 32, 58]],

       [[75, 74, 61],
        [14, 26, 49],
        [72, 42, 19],
        [81, 75, 69],
        [14, 94, 77]]])

In [45]:
print("Minimum of a:", a.min())
print("Maximum of b:", b.max())

Minimum of a: 6
Maximum of b: 95


# Index and Slicing

In [46]:
arr=np.arange(13,30)
print("Array:",arr)

Array: [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


In [47]:
print(arr[7])

20


In [48]:
print(arr[3:6])

[16 17 18]


In [49]:
abc=arr[4:]
abc

array([17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [50]:
arr[-1::-2]

array([29, 27, 25, 23, 21, 19, 17, 15, 13])

In [51]:
arr[-1:-8:-1]

array([29, 28, 27, 26, 25, 24, 23])

In [52]:
arr[[2,4,9]]

array([15, 17, 22])

In [53]:
arr=np.arange(0,21,2)
print("New array:",arr)

New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [54]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
mat[1][2]

6

In [56]:
mat[2]

array([7, 8, 9])

In [57]:
mat[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [58]:
mat[:,1:2]

array([[2],
       [5],
       [8]])

In [59]:
mat[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
mat[0:2,[0,2]]

array([[1, 3],
       [4, 6]])

In [61]:
mat[[1,2],[0,2]]

array([4, 9])

# Subseting

In [62]:
sat=np.array(ri(10,100,15)).reshape(3,5)
sat

array([[72, 10, 86, 79, 95],
       [64, 14, 43, 69, 19],
       [72, 18, 35, 19, 79]])

In [63]:
print(sat[sat>50])

[72 86 79 95 64 69 72 79]


In [64]:
sat>50

array([[ True, False,  True,  True,  True],
       [ True, False, False,  True, False],
       [ True, False, False, False,  True]])

# Slicing

In [65]:
nat=np.array([[11,12,13],[21,22,23],[31,32,33]])
nat

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [66]:
nat1=nat[:2,:2]
nat1

array([[11, 12],
       [21, 22]])

In [67]:
nat1[0,0]=100
print(nat1)
print("\n",nat)

[[100  12]
 [ 21  22]]

 [[100  12  13]
 [ 21  22  23]
 [ 31  32  33]]


# Universal Functions

In [68]:
a1=np.array(ri(1,10,9).reshape(3,3))
a2=np.array(ri(1,10,9).reshape(3,3))
print("a1:\n",a1)
print("\n")
print("a2:\n",a2)

a1:
 [[8 6 9]
 [1 5 5]
 [5 3 2]]


a2:
 [[7 8 8]
 [2 4 5]
 [1 1 7]]


In [69]:
a1+a2

array([[15, 14, 17],
       [ 3,  9, 10],
       [ 6,  4,  9]])

In [70]:
a1*a2

array([[56, 48, 72],
       [ 2, 20, 25],
       [ 5,  3, 14]])

In [71]:
a1-a2

array([[ 1, -2,  1],
       [-1,  1,  0],
       [ 4,  2, -5]])

In [72]:
a1/a2

array([[1.14285714, 0.75      , 1.125     ],
       [0.5       , 1.25      , 1.        ],
       [5.        , 3.        , 0.28571429]])

In [73]:
3*a1+2*a2

array([[38, 34, 43],
       [ 7, 23, 25],
       [17, 11, 20]])

In [74]:
a3=a1[:,:1]
a3

array([[8],
       [1],
       [5]])

In [75]:
a1

array([[8, 6, 9],
       [1, 5, 5],
       [5, 3, 2]])

In [76]:
a1+a3

array([[16, 14, 17],
       [ 2,  6,  6],
       [10,  8,  7]])

In [77]:
a1*a3

array([[64, 48, 72],
       [ 1,  5,  5],
       [25, 15, 10]])

In [78]:
a1**2

array([[64, 36, 81],
       [ 1, 25, 25],
       [25,  9,  4]], dtype=int32)

In [79]:
pow(a1,0.5)

array([[2.82842712, 2.44948974, 3.        ],
       [1.        , 2.23606798, 2.23606798],
       [2.23606798, 1.73205081, 1.41421356]])

In [80]:
a1

array([[8, 6, 9],
       [1, 5, 5],
       [5, 3, 2]])

In [81]:
a2

array([[7, 8, 8],
       [2, 4, 5],
       [1, 1, 7]])

# Broadcasting

In [82]:
st=np.zeros((3,3))
st

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [83]:
ad=np.array([1,0,2])
ad

array([1, 0, 2])

In [84]:
st+ad

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [85]:
ad1=np.array([[0,1,2,3]])
ad1=ad1.T
ad1

array([[0],
       [1],
       [2],
       [3]])